### ISSUE TITLE
为什么使用状态方程预估得到的soc为SoC_real？

### ISSUE THREAD

**Issue by Frankcsc** [AlterWL/Battery_SOC_Estimation#12]
程序中貌似认定通过状态空间方程预估得到的soc为真实值，且在AH、EKF、UKF的Error计算中使用SoC_real作为基准值。
请问这一做法的依据是什么？
如果通过状态空间方程预估得到的soc为真实值，那么为什么需要AH、EKF、UKF一系列方法呢？

**Comment by AlterWL** [comment]
状态方程表示了电池模型，这里的预设是模型可以(近似地)表示电池行为。所以仿真过程把模型的输出，即状态方程的输出，(近似)看做电池的实际输出。然后再将模型的输出加上噪声，作为实际观测值，输入到估计算法，这样来仿真不同算法的估计结果。

因此，这个仿真只是验证的是：默认电池模型近似能力满足要求的情况下，不同算法的有效性。

更严谨的做法是，使用实际的电池观测值，而不是模型仿真(加噪声)值作为算法输入。不过这是有两个问题需要考虑：

1. 卡尔曼算法所需的过程噪声难以确认。
2. 没有soc真实值做参考。

这也是我用模型输出作为电池输出的原因。这样的话过程噪声可以直接在模型里设定，卡尔曼算法中只需要与设定保持一致即可。而模型的soc仿真值就可以看做真实值值

**Comment by nishgovinnd** [comment]
how to identify process noise for a real battery sir

**Comment by Frankcsc** [comment]
> how to identify process noise for a real battery sir

作者的噪声可能是测量出来的吧，现在我在做的东西没有可以测量的途径，也还在想有什么其他的途径可以确定。

**Comment by AlterWL** [comment]
Short answer is I have no idea. I just preset the process noise in the model and use the same value during simulation.

**Comment by nishgovinnd** [comment]
> Short answer is I have no idea. I just preset the process noise in the model and use the same value during simulation.

Thanks Alterwl I too took a similar approach then. But I it still is boggling my mind on how to do it. I tried taking some battery test in uni lab as my battery was a generic one and didn't have any data online, but it also didn't work.
