### ISSUE TITLE
请求您的联系方式

### ISSUE THREAD

**Issue by LT-Rock** [AlterWL/Battery_SOC_Estimation#2]
我想要使用您的开源项目，想私下里交流一下，但是没找到您的联系方式。我的邮箱：LT_Rock@outlook.com
谢谢！

**Comment by AlterWL** [comment]
谢谢您的关注，我会尽快邮箱回复您的。

**Comment by pfangfang** [comment]
对于仿真图我有几个问题想请教一下，希望能得到您的回复。我的邮箱：1176477958@qq.com，谢谢

**Comment by AlterWL** [comment]
好的我会尽快回复您的。

**Comment by pfangfang** [comment]
尊敬先生：
 &nbsp;&nbsp; &nbsp; 您好，对于程序我有以下几点理解和疑问：
 1、simulink仿真：ImprovedSim是对映m文件中代码的仿真电路，示波器输出和matlab绘图结果一致，而且都采用BBDST电流作为输入。另一幅EKFSim的图是什么作用？而且它的输入电压、电流是怎么确定的呢？
 2、m文件代码：Rp、Cp、UOC-upd等的数据都是怎么得到的？通过对thevenin等效电路的参数辨识吗？
 3、资料查询：我在网上找不到公开的电池数据，例如您用到的BBDST工况电流，是从哪找到的呢？
 &nbsp;&nbsp; &nbsp; 由于我以前没有接触过这方面，所以可能问的问题也比较简单、幼稚，希望能得到您的解答。

**Comment by AlterWL** [comment]
Hi pfangfang,
我就直接在这里回答您吧，这样其他人也能看到。
1、EKFSim的仿真是我的第一次尝试，因为仿真效果不太好，所以我在第二次换了一种方式也就是ImprovedSim的图。第一次我是直接使用HPPC测试的实验数据作为电流电压输入，用来测试EKF的估计效果，然后结果表明EKF并不能很好的估计实际状态，尤其是在电流变化剧烈的时候（脉冲充放电阶段）。所以第二次我用了BBDST的实验过程来作为输入，同时电压数据直接使用模型输出加噪声生成，效果一下好了很多。
2、是的，所有文件里的模型参数都是由实际实验数据计算来的，也就是从HPPC测试实验通过参数辨识得到的。
3、BBDST的数据是我当时从实验室师兄那里要的，他是从论文上找到的这种工况，是针对于公交车电池包的工况，我在项目里对电流的幅值做了调整以适应我的电池容量。我现在已经离开实验室了，也只记得这些了，原数据我这里也丢失了，。
谢谢您的关注，我的回答仅仅根据自己的认识，有不完整之处请多谅解。有些信息可以从项目介绍里找到，项目介绍是英文的，这样看起来可能不太友好，这也提醒了我，应该加一份中文的介绍上去了。

**Comment by pfangfang** [comment]
非常感谢您的耐心回复，对我帮助很大，谢谢！
