### ISSUE TITLE
More information on the information you have modelled this on

### ISSUE THREAD

**Issue by nikhil-supreeth** [AlterWL/Battery_SOC_Estimation#5]
Hi AlterWL,
Can you share with me from where you have found these equations to model?
Your work is of great information, very clear compared to many other papers.
Please can you share information from where you have taken these equations as well as if you could share the functions you have used in the thevenin model and the EKF model?
I am still not clear on the UKF so if you could give me all the data you can on these would be of great help for me.
I have about 21 errors running my data on this can you help me?

![5 Matlab Errors Thevenin plus EKF](https://user-images.githubusercontent.com/87434255/127180588-ee7b48cb-8044-412f-9a6d-7a542679d178.png)
![4 Matlab Errors Thevenin plus EKF](https://user-images.githubusercontent.com/87434255/127180591-12186236-9fad-47f6-9256-2c3e2e7da580.png)
![3 Matlab Errors Thevenin plus EKF](https://user-images.githubusercontent.com/87434255/127180592-fe0a1401-ebb0-48a6-ae5b-e37e88d9c6c2.png)
![2 Matlab Errors Thevenin plus EKF](https://user-images.githubusercontent.com/87434255/127180593-3ad61e58-a014-4407-8c32-0924d1e7832b.png)
![1 Matlab Errors Thevenin plus EKF](https://user-images.githubusercontent.com/87434255/127180596-df512465-7d2f-4145-b088-625a8350ca1a.png)

Looking to hear from you soon.
Thanks in advance,
Nikhil Supreeth

**Comment by AlterWL** [comment]
Actually I foregt a lot about this project. I may need to review the project, but not for a while.
So, I'm sorry to say I can't solve your problem in detail, at least not recently.
I add some information about the Thevenin ECM and EKF.
I still don't really understand how UKF works, The realization of this algorithm was done by a friend of mine.
I reorganized the code, hope that it looks a little bit clearer.
