### ISSUE TITLE
部分操作不理解

### ISSUE THREAD

**Issue by chaozijian** [AlterWL/Battery_SOC_Estimation#7]
![1099b2607fcc7ca97bcb5d7b40d29e6](https://user-images.githubusercontent.com/81843375/179436300-fe95e9a8-ffc2-44f8-9f0d-b6e2d5fb3f8d.png)
请问为什么要对电流值做*1.5/50的操作呀，50是安时容量，但是为什么要这么处理

**Comment by AlterWL** [comment]
BBDST工况模块中的电流数据来自50AH容量电池的测试实验，而EKF_UKF_Thev中设置的电池容量为1.5AH，这里做了一个换算。

![图片](https://user-images.githubusercontent.com/39755481/181246344-00616477-660f-4e21-9704-5c058f2c47f4.png)

![图片](https://user-images.githubusercontent.com/39755481/181246039-096a9c44-50af-4163-ad3e-2d3f8522ea4b.png)
