### ISSUE TITLE
SOC initialization

### ISSUE THREAD

**Issue by Astor00** [AlterWL/Battery_SOC_Estimation#9]
How to change the initial SOC value in simulink model ?....I just want to check the convergence of EKF model

**Comment by AlterWL** [comment]
Improved_EKFSim->EKF->Unit Delay Block for SOC_upd.
![图片](https://user-images.githubusercontent.com/39755481/201466619-6e1c25d7-be5b-4b6e-ba15-e476ed028bea.png)
